// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsuHL0PXEgLqgtpcq3Z3DqylgAMHThG08',
    appId: '1:335430690673:web:363f994bc4a0792c1c38d0',
    messagingSenderId: '335430690673',
    projectId: 'nadeem-home-puzzles',
    authDomain: 'nadeem-home-puzzles.firebaseapp.com',
    databaseURL: 'https://nadeem-home-puzzles-default-rtdb.firebaseio.com',
    storageBucket: 'nadeem-home-puzzles.firebasestorage.app',
    measurementId: 'G-YHH83BBYTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvt89AqQnuXZ3dS61JXAavei3hVmi8mpk',
    appId: '1:335430690673:android:1cc9514d167029681c38d0',
    messagingSenderId: '335430690673',
    projectId: 'nadeem-home-puzzles',
    databaseURL: 'https://nadeem-home-puzzles-default-rtdb.firebaseio.com',
    storageBucket: 'nadeem-home-puzzles.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAbJZdFpDcrKoYkZ1w7aeUazi6w-p9FrA',
    appId: '1:335430690673:ios:6b304af2fdeccc201c38d0',
    messagingSenderId: '335430690673',
    projectId: 'nadeem-home-puzzles',
    databaseURL: 'https://nadeem-home-puzzles-default-rtdb.firebaseio.com',
    storageBucket: 'nadeem-home-puzzles.firebasestorage.app',
    iosBundleId: 'com.example.advancedChat',
  );
}
